/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import net.minestom.server.Bootstrap;

public class LaunchItemizeTest {
    public static void main(String... args) {
    	Bootstrap.bootstrap("main.ItemizeTest", args);
    }
}
